package inspector

func (s *service) Symbols() ([]string, error) {
	return []string{
		"BTCUSDT", "ETHUSDT", "LTCUSDT", "ATOMUSDT", "DOTUSDT", "OPUSDT", "DOGEUSDT", "APTUSDT",
		"IMXUSDT", "SOLUSDT", "ARBUSDT", "TRONUSDT", "ADAUSDT", "TONUSDT", "HFTUSDT", "KAVAUSDT",
		"SNXUSDT", "NEOUSDT", "XRPUSDT", "EOSUSDT", "TRXUSDT", "VENUSDT", "VETUSDT", "LINKUSDT",
		"WAVEUSDT", "BATUSDT", "XMRUSDT", "CELRUSDT", "DASHUSDT", "ALGOUSDT", "BANDUSDT", "CHRUSDT",
	}, nil
}
